import { useListModels, useListDatasets, useRunJudge, getListEvaluationsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { FileCheck2, CheckCircle2, XCircle, AlertCircle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";

export default function Evaluate() {
  const { data: models, isLoading: isLoadingModels } = useListModels();
  const { data: datasets, isLoading: isLoadingDatasets } = useListDatasets();
  const runJudge = useRunJudge();
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const [selectedJudgeId, setSelectedJudgeId] = useState<string>("");
  const [selectedDatasetId, setSelectedDatasetId] = useState<string>("");
  const [selectedModelId, setSelectedModelId] = useState<string>(""); // optional filter
  const [result, setResult] = useState<{ evaluated: number; skipped: number; errors: string[] } | null>(null);

  function handleEvaluate() {
    if (!selectedJudgeId || !selectedDatasetId) return;

    setResult(null);

    runJudge.mutate(
      {
        data: {
          judgeModelId: parseInt(selectedJudgeId),
          datasetId: parseInt(selectedDatasetId),
          modelId: selectedModelId ? parseInt(selectedModelId) : undefined,
        },
      },
      {
        onSuccess: (res) => {
          setResult(res);
          queryClient.invalidateQueries({ queryKey: getListEvaluationsQueryKey() });
          toast({
            title: "Evaluation Complete",
            description: `Evaluated ${res.evaluated} responses.`,
          });
        },
        onError: (err) => {
          toast({
            title: "Evaluation Failed",
            description: err.error || "Unknown error occurred",
            variant: "destructive",
          });
        },
      }
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div>
        <h2 className="text-3xl font-bold tracking-tight">LLM-as-a-Judge</h2>
        <p className="text-muted-foreground">Use a stronger LLM to score responses generated by other models.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="md:col-span-2">
          <CardHeader>
            <CardTitle>Run Evaluation Pipeline</CardTitle>
            <CardDescription>Select judge and target data to evaluate.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="space-y-4">
              <div className="space-y-2">
                <Label className="text-primary font-semibold">Judge Model</Label>
                {isLoadingModels ? (
                  <Skeleton className="h-10 w-full" />
                ) : (
                  <Select value={selectedJudgeId} onValueChange={setSelectedJudgeId}>
                    <SelectTrigger className="border-primary ring-primary">
                      <SelectValue placeholder="Select the model that will act as the judge" />
                    </SelectTrigger>
                    <SelectContent>
                      {models?.map((m) => (
                        <SelectItem key={m.id} value={m.id.toString()}>
                          {m.modelName} ({m.provider})
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Dataset</Label>
                  {isLoadingDatasets ? (
                    <Skeleton className="h-10 w-full" />
                  ) : (
                    <Select value={selectedDatasetId} onValueChange={setSelectedDatasetId}>
                      <SelectTrigger>
                        <SelectValue placeholder="Select dataset" />
                      </SelectTrigger>
                      <SelectContent>
                        {datasets?.map((d) => (
                          <SelectItem key={d.id} value={d.id.toString()}>
                            {d.datasetName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                </div>

                <div className="space-y-2">
                  <Label>Filter Target Model (Optional)</Label>
                  {isLoadingModels ? (
                    <Skeleton className="h-10 w-full" />
                  ) : (
                    <Select value={selectedModelId} onValueChange={setSelectedModelId}>
                      <SelectTrigger>
                        <SelectValue placeholder="All models" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="all">All Models</SelectItem>
                        {models?.map((m) => (
                          <SelectItem key={m.id} value={m.id.toString()}>
                            {m.modelName}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  )}
                </div>
              </div>
            </div>

            <Button
              className="w-full h-12 text-lg bg-primary hover:bg-primary/90 text-primary-foreground"
              onClick={handleEvaluate}
              disabled={runJudge.isPending || !selectedJudgeId || !selectedDatasetId}
            >
              <FileCheck2 className="mr-2 h-5 w-5" />
              {runJudge.isPending ? "Running Evaluation..." : "Run Judge"}
            </Button>

            {result && (
              <div className="mt-6 space-y-4 animate-in fade-in slide-in-from-bottom-4">
                <h3 className="text-lg font-medium border-b border-border pb-2">Results</h3>
                <div className="grid grid-cols-2 gap-4">
                  <Card className="bg-primary/10 border-primary/20">
                    <CardContent className="p-4 flex flex-col items-center justify-center">
                      <CheckCircle2 className="h-8 w-8 text-primary mb-2" />
                      <div className="text-3xl font-bold">{result.evaluated}</div>
                      <div className="text-sm text-muted-foreground">Evaluated</div>
                    </CardContent>
                  </Card>
                  <Card className="bg-muted/50">
                    <CardContent className="p-4 flex flex-col items-center justify-center">
                      <AlertCircle className="h-8 w-8 text-muted-foreground mb-2" />
                      <div className="text-3xl font-bold">{result.skipped}</div>
                      <div className="text-sm text-muted-foreground">Skipped (Already scored)</div>
                    </CardContent>
                  </Card>
                </div>

                {result.errors.length > 0 && (
                  <Alert variant="destructive">
                    <XCircle className="h-4 w-4" />
                    <AlertTitle>Errors Encountered</AlertTitle>
                    <AlertDescription>
                      <ul className="list-disc pl-4 mt-2 max-h-40 overflow-y-auto">
                        {result.errors.map((err, i) => (
                          <li key={i} className="text-xs font-mono">{err}</li>
                        ))}
                      </ul>
                    </AlertDescription>
                  </Alert>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="md:col-span-1 h-fit">
          <CardHeader>
            <CardTitle className="text-sm">Scoring Rubric</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex flex-col gap-3">
              <div className="flex items-start gap-3 text-sm">
                <Badge className="bg-red-500 hover:bg-red-600 mt-0.5 shrink-0">1</Badge>
                <div>
                  <span className="font-semibold block">Critical Error</span>
                  <span className="text-muted-foreground text-xs">Hallucination, factual error, or completely missed instruction.</span>
                </div>
              </div>
              <div className="flex items-start gap-3 text-sm">
                <Badge className="bg-orange-500 hover:bg-orange-600 mt-0.5 shrink-0">2</Badge>
                <div>
                  <span className="font-semibold block">Weak</span>
                  <span className="text-muted-foreground text-xs">Major omissions or poor reasoning structure.</span>
                </div>
              </div>
              <div className="flex items-start gap-3 text-sm">
                <Badge className="bg-yellow-500 hover:bg-yellow-600 mt-0.5 shrink-0">3</Badge>
                <div>
                  <span className="font-semibold block">Partial</span>
                  <span className="text-muted-foreground text-xs">Acceptable but unrefined, or missing key nuance.</span>
                </div>
              </div>
              <div className="flex items-start gap-3 text-sm">
                <Badge className="bg-cyan-500 hover:bg-cyan-600 mt-0.5 shrink-0">4</Badge>
                <div>
                  <span className="font-semibold block">Good</span>
                  <span className="text-muted-foreground text-xs">Strong response, minor stylistic or detail issues.</span>
                </div>
              </div>
              <div className="flex items-start gap-3 text-sm">
                <Badge className="bg-green-500 hover:bg-green-600 mt-0.5 shrink-0">5</Badge>
                <div>
                  <span className="font-semibold block">Excellent</span>
                  <span className="text-muted-foreground text-xs">Matches or exceeds gold standard. Perfect instruction following.</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}