import { motion } from "framer-motion";
import { ArrowRight, Brain, Users, BarChart3, AlertTriangle, Flag, CheckCircle2, Info, BookOpen, GitBranch, Scale, Sigma } from "lucide-react";

// ── Pipeline Step ─────────────────────────────────────────────────────────────

const PIPELINE = [
  { icon: "📂", label: "Dataset",           sub: "Medical QA questions\n(MCQ + Open-Ended)" },
  { icon: "🤖", label: "Candidate SLM",     sub: "Small Language Model\ngenerates a response" },
  { icon: "📖", label: "LLM Reference",     sub: "Synthetic Reference\ngenerated by a Judge LLM" },
  { icon: "⚖️",  label: "Judge Evaluation", sub: "LLM-as-a-Judge scores\nthe SLM response (1–5)" },
  { icon: "👤", label: "Human Evaluation",  sub: "Human reviewers score\nthe same responses (1–5)" },
  { icon: "📊", label: "Spearman ρ",        sub: "Rank correlation between\nJudge and Human scores" },
  { icon: "🔍", label: "Disagreement",      sub: "Cases where |Human − Judge|\n≥ 2 are surfaced" },
  { icon: "💡", label: "Research Insights", sub: "Bias patterns, failure modes\nand reliability metrics" },
];

// ── Flag taxonomy ─────────────────────────────────────────────────────────────

const FLAGS = [
  {
    type: "PROMPT_LEAKAGE",
    label: "Prompt Leakage",
    color: "text-red-700", bg: "bg-red-50", border: "border-red-200",
    icon: "🔓",
    description: "The model echoed or paraphrased parts of the system or user prompt verbatim instead of reasoning independently.",
    example: `Response begins with "As per the instructions, the answer is…" — repeating instructions rather than providing medical reasoning.`,
    impact: "Inflates perceived quality. Judge may award high scores to formally structured but content-empty answers.",
  },
  {
    type: "HALLUCINATION",
    label: "Hallucination",
    color: "text-purple-700", bg: "bg-purple-50", border: "border-purple-200",
    icon: "🌀",
    description: "The model fabricated medical facts, drug names, dosages, or clinical guidelines not grounded in evidence.",
    example: `"The standard dose of X is 500 mg IV every 4 hours" — when no such guideline exists.`,
    impact: "Critical in medical NLP. May cause Judge overrating if the fabrication is linguistically fluent and confident.",
  },
  {
    type: "OVER_VERBOSE",
    label: "Over-Verbose",
    color: "text-amber-700", bg: "bg-amber-50", border: "border-amber-200",
    icon: "📝",
    description: "The response is excessively long, padded with filler sentences or redundant caveats that obscure the actual answer.",
    example: "A three-paragraph response to a yes/no clinical question, with no additional diagnostic value.",
    impact: "Strongly linked to Judge overrating. LLM judges may conflate length and elaboration with quality.",
  },
  {
    type: "FACTUAL_ERROR",
    label: "Factual Error",
    color: "text-orange-700", bg: "bg-orange-50", border: "border-orange-200",
    icon: "❌",
    description: "The response contains a verifiably incorrect statement — wrong diagnosis, contraindicated treatment, or wrong drug class.",
    example: `"Beta-blockers are the first-line treatment for acute asthma exacerbation."`,
    impact: "Dangerous in clinical settings. Often correlated with low human scores but occasionally missed by LLM judges.",
  },
  {
    type: "PARTIAL_ANSWER",
    label: "Partial Answer",
    color: "text-blue-700", bg: "bg-blue-50", border: "border-blue-200",
    icon: "⚡",
    description: "The response addresses only part of the question, omitting key clinical components such as differential diagnosis, treatment plan, or contraindications.",
    example: "Question asks for diagnosis and management; response gives only the diagnosis.",
    impact: "Common source of underrating. Judges may still score generously if the answered portion is correct.",
  },
  {
    type: "OFF_TOPIC",
    label: "Off-Topic",
    color: "text-slate-700", bg: "bg-slate-50", border: "border-slate-200",
    icon: "↗️",
    description: "The response does not address the clinical question asked, either pivoting to a different condition or providing generic medical information.",
    example: "Question about cardiac arrhythmia management; response discusses general cardiovascular health.",
    impact: "Typically produces strong disagreement. Human reviewers detect irrelevance easily; LLM judges sometimes do not.",
  },
];

// ── Spearman interpretation table ─────────────────────────────────────────────

const SPEARMAN_TABLE = [
  { range: "0.90 – 1.00", label: "Very Strong Agreement",  color: "text-green-700",  bg: "bg-green-50",  desc: "Judge and human rankings are nearly identical. High reliability for deployment." },
  { range: "0.70 – 0.89", label: "Strong Agreement",       color: "text-green-600",  bg: "bg-green-50",  desc: "Minor rank differences. Judge is reliable but not perfect." },
  { range: "0.50 – 0.69", label: "Moderate Agreement",     color: "text-amber-700",  bg: "bg-amber-50",  desc: "Noticeable systematic differences. Review judge prompt and rubric." },
  { range: "0.30 – 0.49", label: "Weak Agreement",         color: "text-orange-700", bg: "bg-orange-50", desc: "Significant judge bias detected. Investigate disagreement cases." },
  { range: "0.00 – 0.29", label: "Very Weak Agreement",    color: "text-red-600",    bg: "bg-red-50",    desc: "Judge rankings are largely uncorrelated with human judgment." },
  { range: "< 0.00",      label: "Disagreement",           color: "text-red-700",    bg: "bg-red-50",    desc: "Judge systematically inverts human rankings. Severe prompt or rubric issue." },
];

// ── Section wrapper ───────────────────────────────────────────────────────────

function Section({ id, title, icon, children }: {
  id: string; title: string; icon: React.ReactNode; children: React.ReactNode;
}) {
  return (
    <motion.section
      id={id}
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      className="scroll-mt-6"
    >
      <div className="flex items-center gap-2.5 mb-5">
        <div className="w-8 h-8 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
          {icon}
        </div>
        <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      </div>
      {children}
    </motion.section>
  );
}

function InfoBox({ children, color = "blue" }: { children: React.ReactNode; color?: "blue" | "amber" | "green" }) {
  const cls = {
    blue:  "bg-blue-50 border-blue-200 text-blue-900",
    amber: "bg-amber-50 border-amber-200 text-amber-900",
    green: "bg-green-50 border-green-200 text-green-900",
  }[color];
  return (
    <div className={`flex gap-2.5 p-3.5 rounded-lg border text-sm leading-relaxed ${cls}`}>
      <Info className="h-4 w-4 shrink-0 mt-0.5 opacity-70" />
      <div>{children}</div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function Methodology() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      className="space-y-10 max-w-4xl"
    >
      {/* Header */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <BookOpen className="h-5 w-5 text-primary" />
          <h1 className="text-2xl font-bold">Methodology</h1>
        </div>
        <p className="text-sm text-muted-foreground max-w-2xl leading-relaxed">
          Academic documentation for the MedEval Judge evaluation framework — covering the system pipeline,
          evaluation methodology, error taxonomy, and statistical reliability metrics.
        </p>
      </div>

      {/* ── 1. System Pipeline ── */}
      <Section id="pipeline" title="System Pipeline" icon={<GitBranch className="h-4 w-4 text-primary" />}>
        <p className="text-sm text-muted-foreground mb-6 leading-relaxed">
          The evaluation pipeline transforms raw medical questions into actionable research insights
          through a multi-stage process combining automated and human-in-the-loop evaluation.
        </p>

        {/* Visual pipeline */}
        <div className="relative">
          <div className="flex flex-wrap items-start gap-0">
            {PIPELINE.map((step, i) => (
              <div key={i} className="flex items-center">
                <div className="flex flex-col items-center w-[110px] sm:w-[120px]">
                  <div className="w-14 h-14 rounded-2xl bg-white border-2 border-border shadow-sm flex items-center justify-center text-2xl mb-2">
                    {step.icon}
                  </div>
                  <p className="text-xs font-semibold text-center text-foreground leading-tight mb-0.5">{step.label}</p>
                  <p className="text-[10px] text-muted-foreground text-center leading-tight whitespace-pre-line">{step.sub}</p>
                </div>
                {i < PIPELINE.length - 1 && (
                  <ArrowRight className="h-4 w-4 text-muted-foreground/40 mb-8 mx-1 shrink-0" />
                )}
              </div>
            ))}
          </div>
        </div>

        <div className="mt-6 grid gap-3 sm:grid-cols-2">
          <InfoBox color="blue">
            <strong>LLM Reference ≠ Ground Truth.</strong> The LLM-generated reference answer is a
            <em> Synthetic Reference</em> used to guide judge scoring. The true gold standard is the
            original annotated answer from the dataset.
          </InfoBox>
          <InfoBox color="green">
            <strong>Human-in-the-loop validation</strong> is the key differentiator from traditional
            automated metrics (BLEU, ROUGE). Human scores provide the ground truth for measuring judge reliability.
          </InfoBox>
        </div>
      </Section>

      {/* ── 2. Evaluation Methodology ── */}
      <Section id="methodology" title="Evaluation Methodology" icon={<Scale className="h-4 w-4 text-primary" />}>
        <div className="space-y-5">

          {/* Scoring rubric */}
          <div>
            <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">1</span>
              Judge Scoring Rubric (1–5)
            </h3>
            <div className="rounded-xl overflow-hidden border border-border">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-muted/40 border-b border-border">
                    <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide w-16">Score</th>
                    <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide w-32">Label</th>
                    <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide">Criteria</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    { s: 5, label: "Excellent",  color: "text-green-700",  desc: "Fully correct, complete, and well-reasoned. Matches or exceeds the reference answer." },
                    { s: 4, label: "Good",        color: "text-blue-700",   desc: "Mostly correct with minor omissions. Clinically acceptable with small gaps." },
                    { s: 3, label: "Partial",     color: "text-amber-700",  desc: "Partially correct. Captures the main idea but misses key clinical details." },
                    { s: 2, label: "Weak",        color: "text-orange-700", desc: "Mostly incorrect or incomplete. Shows limited understanding of the question." },
                    { s: 1, label: "Critical",    color: "text-red-700",    desc: "Completely incorrect, irrelevant, or potentially harmful in a clinical context." },
                  ].map((r, i) => (
                    <tr key={r.s} className={`border-b border-border last:border-0 ${i % 2 === 0 ? "" : "bg-muted/20"}`}>
                      <td className="px-4 py-3">
                        <span className={`text-base font-bold tabular-nums ${r.color}`}>{r.s}</span>
                      </td>
                      <td className={`px-4 py-3 font-semibold text-sm ${r.color}`}>{r.label}</td>
                      <td className="px-4 py-3 text-sm text-muted-foreground leading-relaxed">{r.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Human averages */}
          <div>
            <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">2</span>
              Computing Human Average Scores
            </h3>
            <div className="bg-white border border-border rounded-xl p-4 space-y-3">
              <p className="text-sm text-muted-foreground leading-relaxed">
                When multiple human reviewers evaluate the same response, the system computes a simple
                arithmetic mean of all submitted scores:
              </p>
              <div className="bg-muted/40 rounded-lg px-4 py-3 font-mono text-sm text-center">
                Human<sub>avg</sub> = (s₁ + s₂ + … + sₙ) / n
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                This average is then compared against the judge score to compute the disagreement delta
                (Δ) and to build the Spearman rank correlation.
              </p>
            </div>
          </div>

          {/* Disagreement definition */}
          <div>
            <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">3</span>
              Disagreement Detection Threshold
            </h3>
            <div className="bg-white border border-border rounded-xl p-4 space-y-3">
              <div className="bg-muted/40 rounded-lg px-4 py-3 font-mono text-sm text-center">
                Disagreement := |Human<sub>avg</sub> − Judge<sub>score</sub>| ≥ 2
              </div>
              <div className="grid gap-3 sm:grid-cols-2 text-sm">
                <div className="p-3 rounded-lg bg-amber-50 border border-amber-200">
                  <p className="font-semibold text-amber-800 mb-1 flex items-center gap-1">
                    <span>↑</span> Overrating
                  </p>
                  <p className="text-amber-700 text-xs leading-relaxed">
                    Judge score &gt; Human average. The judge is more lenient than human reviewers —
                    may indicate sensitivity to response style, verbosity, or lexical similarity with the reference.
                  </p>
                </div>
                <div className="p-3 rounded-lg bg-blue-50 border border-blue-200">
                  <p className="font-semibold text-blue-800 mb-1 flex items-center gap-1">
                    <span>↓</span> Underrating
                  </p>
                  <p className="text-blue-700 text-xs leading-relaxed">
                    Judge score &lt; Human average. The judge is more strict than human reviewers —
                    may indicate failure in semantic understanding or paraphrase detection.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Section>

      {/* ── 3. Error Taxonomy ── */}
      <Section id="flags" title="Error Taxonomy — Quality Flags" icon={<Flag className="h-4 w-4 text-primary" />}>
        <p className="text-sm text-muted-foreground mb-5 leading-relaxed">
          Quality flags annotate specific failure modes in model responses. They enable structured
          error analysis and help explain systematic disagreements between judge and human evaluators.
        </p>

        <div className="space-y-3">
          {FLAGS.map((f) => (
            <div key={f.type} className={`rounded-xl border ${f.border} ${f.bg} overflow-hidden`}>
              <div className="flex items-start gap-3 p-4">
                <span className="text-2xl shrink-0 mt-0.5">{f.icon}</span>
                <div className="flex-1 space-y-2">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className={`font-mono text-xs font-bold px-2 py-0.5 rounded border ${f.border} bg-white ${f.color}`}>
                      {f.type}
                    </span>
                    <span className={`text-sm font-semibold ${f.color}`}>{f.label}</span>
                  </div>
                  <p className="text-sm leading-relaxed">{f.description}</p>
                  <div className="grid gap-2 sm:grid-cols-2 text-xs">
                    <div className="bg-white/70 rounded-lg p-2.5 border border-white/80">
                      <p className="font-semibold text-muted-foreground mb-1 uppercase tracking-wide text-[10px]">Example</p>
                      <p className="leading-relaxed italic text-foreground/70">{f.example}</p>
                    </div>
                    <div className="bg-white/70 rounded-lg p-2.5 border border-white/80">
                      <p className="font-semibold text-muted-foreground mb-1 uppercase tracking-wide text-[10px]">Impact on Judge</p>
                      <p className="leading-relaxed text-foreground/70">{f.impact}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* ── 4. Judge Reliability ── */}
      <Section id="reliability" title="Judge Reliability — Statistical Interpretation" icon={<Sigma className="h-4 w-4 text-primary" />}>
        <div className="space-y-5">

          {/* Spearman explanation */}
          <div>
            <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">ρ</span>
              Spearman Rank Correlation
            </h3>
            <div className="bg-white border border-border rounded-xl p-4 space-y-3 text-sm text-muted-foreground leading-relaxed">
              <p>
                Spearman's ρ (rho) measures the degree of rank-order agreement between judge scores
                and human average scores. Unlike Pearson's r, it is robust to outliers and does not
                assume a linear relationship — making it appropriate for ordinal evaluation scales (1–5).
              </p>
              <div className="bg-muted/40 rounded-lg px-4 py-3 font-mono text-xs text-center">
                ρ = 1 − (6 Σdᵢ²) / (n(n²−1))
                <span className="block mt-1 text-muted-foreground/60 font-sans normal-case">
                  where dᵢ = rank(human_i) − rank(judge_i)
                </span>
              </div>
              <p>
                A value of <strong className="text-foreground">ρ = 1.0</strong> means perfect agreement in rankings.
                A value of <strong className="text-foreground">ρ = 0.0</strong> means no correlation.
                A value of <strong className="text-foreground">ρ = −1.0</strong> means complete inversion of rankings.
              </p>
            </div>
          </div>

          {/* Interpretation table */}
          <div>
            <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">📊</span>
              Interpretation Reference
            </h3>
            <div className="rounded-xl overflow-hidden border border-border">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-muted/40 border-b border-border">
                    <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide w-32">ρ Range</th>
                    <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide w-48">Interpretation</th>
                    <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide">Recommended Action</th>
                  </tr>
                </thead>
                <tbody>
                  {SPEARMAN_TABLE.map((r, i) => (
                    <tr key={r.range} className={`border-b border-border last:border-0 ${i % 2 === 0 ? "" : "bg-muted/20"}`}>
                      <td className="px-4 py-3 font-mono text-xs font-bold text-foreground">{r.range}</td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-semibold border ${r.bg} ${r.color}`}>
                          {r.label}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-sm text-muted-foreground leading-relaxed">{r.desc}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Bias metrics */}
          <div>
            <h3 className="text-sm font-semibold mb-3 flex items-center gap-2">
              <span className="w-5 h-5 rounded-full bg-primary/10 text-primary text-xs font-bold flex items-center justify-center">⚖️</span>
              Bias Metrics
            </h3>
            <div className="grid gap-3 sm:grid-cols-3 text-sm">
              {[
                {
                  label: "Overrating Rate",
                  formula: "# cases where Judge > Human / N",
                  desc: "Proportion of responses where the judge scored higher than human reviewers by any margin. High overrating suggests the judge rewards style or verbosity.",
                  warn: "> 40% is concerning",
                },
                {
                  label: "Underrating Rate",
                  formula: "# cases where Judge < Human / N",
                  desc: "Proportion of responses where the judge scored lower than humans. High underrating suggests the judge may fail at semantic understanding or paraphrase equivalence.",
                  warn: "> 40% is concerning",
                },
                {
                  label: "Average Δ (Avg Delta)",
                  formula: "Σ |Judge − Human| / N",
                  desc: "Mean absolute difference between judge and human scores. Provides a single-number summary of calibration quality — closer to 0 is better.",
                  warn: "Δ > 1.5 needs review",
                },
              ].map((m) => (
                <div key={m.label} className="bg-white border border-border rounded-xl p-3.5 space-y-2">
                  <p className="font-semibold text-sm">{m.label}</p>
                  <p className="font-mono text-xs bg-muted/40 px-2 py-1.5 rounded text-muted-foreground">{m.formula}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{m.desc}</p>
                  <p className="text-xs font-medium text-amber-700 bg-amber-50 border border-amber-100 rounded px-2 py-1">{m.warn}</p>
                </div>
              ))}
            </div>
          </div>

          <InfoBox color="amber">
            <strong>Statistical significance note:</strong> Spearman ρ should be interpreted cautiously when
            N &lt; 10. With fewer than 3 paired evaluations, correlation cannot be computed. Aim for at
            least 20–30 human-evaluated responses per judge model for robust reliability estimates.
          </InfoBox>
        </div>
      </Section>

      {/* ── Terminology ── */}
      <Section id="terminology" title="Terminology Reference" icon={<Brain className="h-4 w-4 text-primary" />}>
        <div className="rounded-xl overflow-hidden border border-border">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-muted/40 border-b border-border">
                <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide w-48">Term</th>
                <th className="text-left px-4 py-2.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide">Definition</th>
              </tr>
            </thead>
            <tbody>
              {[
                { term: "Gold Answer",            def: "The authoritative reference answer from the original dataset. This is the true ground truth." },
                { term: "LLM / Synthetic Reference", def: "An answer generated by a large Judge LLM to guide scoring. NOT a ground truth — it is a synthetic reference." },
                { term: "SLM (Candidate Model)",  def: "The Small Language Model being evaluated. Its responses are judged against the reference." },
                { term: "Judge Model",            def: "The LLM used to score SLM responses. Acts as an automated evaluator." },
                { term: "LLM-as-a-Judge",         def: "Evaluation paradigm where an LLM judges the quality of another model's outputs." },
                { term: "Human Baseline",         def: "Human-assigned scores that serve as the calibration reference for measuring judge reliability." },
                { term: "Spearman ρ",             def: "Rank-order correlation coefficient between judge and human scores. Values range from −1 to +1." },
                { term: "Disagreement Δ",         def: "|Human_avg − Judge_score|. A delta ≥ 2 triggers disagreement analysis." },
                { term: "Overrating",             def: "Judge assigns a higher score than human reviewers. Associated with leniency bias." },
                { term: "Underrating",            def: "Judge assigns a lower score than human reviewers. Associated with strictness bias or paraphrase failure." },
                { term: "Quality Flag",           def: "A human-assigned label identifying a specific failure mode in a model response." },
              ].map((r, i) => (
                <tr key={r.term} className={`border-b border-border last:border-0 ${i % 2 === 0 ? "" : "bg-muted/20"}`}>
                  <td className="px-4 py-3 font-semibold text-foreground align-top">{r.term}</td>
                  <td className="px-4 py-3 text-muted-foreground leading-relaxed">{r.def}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      {/* Footer note */}
      <div className="text-xs text-muted-foreground border-t border-border pt-5 pb-2">
        MedEval Judge — Human-Aligned LLM Evaluation Research Platform · Academic Documentation
      </div>
    </motion.div>
  );
}
